# Generated by Django 3.2 on 2022-12-29 08:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_pvmessage_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pvmessage',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pvmessage',
            name='pv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='main.pv'),
        ),
    ]
