# Generated by Django 3.2 on 2022-12-15 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1s', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2s', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='groupmember',
            name='can_send_message',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='group/messages/'),
        ),
        migrations.CreateModel(
            name='PVMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(choices=[('1', 'User1'), ('2', 'User2')], max_length=2)),
                ('text', models.TextField(blank=True, null=True)),
                ('media', models.FileField(blank=True, null=True, upload_to='pv/messages/')),
                ('is_deleted', models.BooleanField(default=False)),
                ('pv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pv')),
            ],
        ),
    ]
