# Generated by Django 3.2.25 on 2026-08-30 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='desc',
            field=models.TextField(blank=True),
        ),
    ]
