# Generated by Django 3.2 on 2023-01-03 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_group_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmember',
            name='can_send_message',
        ),
    ]
