# Generated by Django 3.2 on 2022-12-18 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_userprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='register_complete',
            field=models.BooleanField(default=False),
        ),
    ]
